server: 
  port: 8888
auth: 
  loginUrl: /login
  secret: c2VkaW4=
  issuer: burst #token签发者
spring: 
  profiles: 
    active: test
    include: tool #无论何时都讲common包含进来
---
spring: 
  profiles: dev
server: 
  port: 80
auth: 
  open: false
  
  
---
spring: 
  profiles: test
server: 
  port: 8080
auth: 
  open: true
---
spring: 
  profiles: tool
  devtools: 
    restart:
      enable: false #表示是否触发类修改重启