server: 
  port: 8888
auth: 
  secret: 123456
  issuer: burst
spring: 
  profiles: 
    active: test
    include: tool #无论何时都讲common包含进来
---
spring: 
  profiles: dev
server: 
  port: 80
  
---
spring: 
  profiles: test
server: 
  port: 8080

---
spring: 
  profiles: tool
  devtools: 
    restart:
      enable: false #表示是否触发类修改重启