server: 
  port: 8888
spring: 
  profiles: 
    active: test
    include: common #无论何时都讲common包含进来
---
spring: 
  profiles: dev
server: 
  port: 80
  
---
spring: 
  profiles: test
server: 
  port: 8080

---
spring: 
  profiles: common
